# GitHub Issue Labels Configuration
# Use with: gh label sync --file .github/labels.yml

- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "feat"
  color: "0e8a16"
  description: "New feature or request"

- name: "fix"
  color: "d876e3"
  description: "Bug fix"

- name: "docs"
  color: "0075ca"
  description: "Documentation only changes"

- name: "refactor"
  color: "fbca04"
  description: "Code refactoring"

- name: "perf"
  color: "ff6b6b"
  description: "Performance improvements"

- name: "test"
  color: "bfd4f2"
  description: "Adding or updating tests"

- name: "ci"
  color: "1d76db"
  description: "CI/CD changes"

- name: "chore"
  color: "fef2c0"
  description: "Other changes"

- name: "dependencies"
  color: "0366d6"
  description: "Dependency updates"

- name: "web"
  color: "c2e0c6"
  description: "Web app related"

- name: "native"
  color: "bfdadc"
  description: "Native app related"

- name: "server"
  color: "c5def5"
  description: "Server related"

- name: "api"
  color: "d4c5f9"
  description: "API package related"

- name: "auth"
  color: "f9c5d1"
  description: "Auth package related"

- name: "db"
  color: "c5f9e8"
  description: "Database related"

- name: "priority: critical"
  color: "b60205"
  description: "Critical priority"

- name: "priority: high"
  color: "d93f0b"
  description: "High priority"

- name: "priority: medium"
  color: "fbca04"
  description: "Medium priority"

- name: "priority: low"
  color: "0e8a16"
  description: "Low priority"

- name: "breaking-change"
  color: "d73a4a"
  description: "Breaking changes"

- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "question"
  color: "d876e3"
  description: "Further information is requested"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"

- name: "released"
  color: "00ff00"
  description: "Released in a version"

- name: "automerge"
  color: "0e8a16"
  description: "Automatically merge when CI passes"
