packages:
  - apps/*
  - packages/*
catalog:
  hono: ^4.11.3
  "@orpc/server": ^1.13.2
  "@orpc/openapi": ^1.13.2
  "@orpc/zod": ^1.13.2
  better-auth: ^1.4.10
  dotenv: ^17.2.2
  zod: ^4.3.4
  typescript: ^5.8.2
  "@types/node": ^22.13.11
  tsdown: ^0.18.4
  "@orpc/client": ^1.13.2
