packages:
  - apps/*
  - packages/*
catalog:
  hono: ^4.10.6
  "@orpc/server": ^1.11.3
  "@orpc/openapi": ^1.11.3
  "@orpc/zod": ^1.11.3
  better-auth: ^1.3.28
  dotenv: ^17.2.2
  zod: ^4.1.11
  typescript: ^5.8.2
  "@types/node": ^22.13.11
  tsdown: ^0.16.5
  "@orpc/client": ^1.11.3
