packages:
  - apps/*
  - packages/*
catalog:
  hono: ^4.11.4
  "@orpc/server": ^1.13.4
  "@orpc/openapi": ^1.13.4
  "@orpc/zod": ^1.13.4
  better-auth: ^1.4.12
  dotenv: ^17.2.2
  zod: ^4.3.5
  typescript: ^5.8.2
  "@types/node": ^22.13.11
  tsdown: ^0.19.0
  "@orpc/client": ^1.13.4
