packages:
  - apps/*
  - packages/*

catalog:
  '@orpc/client': ^1.13.4
  '@orpc/openapi': ^1.13.4
  '@orpc/server': ^1.13.4
  '@orpc/zod': ^1.13.4
  '@types/node': ^22.13.11
  better-auth: ^1.4.12
  dotenv: ^17.2.2
  hono: ^4.11.4
  tsdown: ^0.19.0
  typescript: ^5.8.2
  zod: ^4.3.5

patchedDependencies:
  better-auth@1.3.34: patches/better-auth@1.3.34.patch
