/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OtpVerificationRouteImport } from './routes/otp-verification'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses/$courseId'
import { Route as AdminVideosIndexRouteImport } from './routes/admin/videos/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminLiveIndexRouteImport } from './routes/admin/live/index'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as AdminLiveStreamIdRouteImport } from './routes/admin/live/$streamId'
import { Route as AdminCoursesCreateRouteImport } from './routes/admin/courses/create'
import { Route as AdminCoursesCourseIdRouteImport } from './routes/admin/courses/$courseId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpVerificationRoute = OtpVerificationRouteImport.update({
  id: '/otp-verification',
  path: '/otp-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminVideosIndexRoute = AdminVideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveIndexRoute = AdminLiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveStreamIdRoute = AdminLiveStreamIdRouteImport.update({
  id: '/live/$streamId',
  path: '/live/$streamId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesCreateRoute = AdminCoursesCreateRouteImport.update({
  id: '/courses/create',
  path: '/courses/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesCourseIdRoute = AdminCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/otp-verification': typeof OtpVerificationRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/courses/create': typeof AdminCoursesCreateRoute
  '/admin/live/$streamId': typeof AdminLiveStreamIdRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/live': typeof AdminLiveIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/videos': typeof AdminVideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/otp-verification': typeof OtpVerificationRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/courses/create': typeof AdminCoursesCreateRoute
  '/admin/live/$streamId': typeof AdminLiveStreamIdRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/live': typeof AdminLiveIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/videos': typeof AdminVideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/otp-verification': typeof OtpVerificationRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/courses/create': typeof AdminCoursesCreateRoute
  '/admin/live/$streamId': typeof AdminLiveStreamIdRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/live/': typeof AdminLiveIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/videos/': typeof AdminVideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/courses'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/otp-verification'
    | '/profile'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/courses/$courseId'
    | '/admin/'
    | '/admin/courses/$courseId'
    | '/admin/courses/create'
    | '/admin/live/$streamId'
    | '/admin/courses'
    | '/admin/live'
    | '/admin/users'
    | '/admin/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/otp-verification'
    | '/profile'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/courses/$courseId'
    | '/admin'
    | '/admin/courses/$courseId'
    | '/admin/courses/create'
    | '/admin/live/$streamId'
    | '/admin/courses'
    | '/admin/live'
    | '/admin/users'
    | '/admin/videos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/courses'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/otp-verification'
    | '/profile'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/courses/$courseId'
    | '/admin/'
    | '/admin/courses/$courseId'
    | '/admin/courses/create'
    | '/admin/live/$streamId'
    | '/admin/courses/'
    | '/admin/live/'
    | '/admin/users/'
    | '/admin/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OtpVerificationRoute: typeof OtpVerificationRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp-verification': {
      id: '/otp-verification'
      path: '/otp-verification'
      fullPath: '/otp-verification'
      preLoaderRoute: typeof OtpVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/videos/': {
      id: '/admin/videos/'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live/': {
      id: '/admin/live/'
      path: '/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live/$streamId': {
      id: '/admin/live/$streamId'
      path: '/live/$streamId'
      fullPath: '/admin/live/$streamId'
      preLoaderRoute: typeof AdminLiveStreamIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/create': {
      id: '/admin/courses/create'
      path: '/courses/create'
      fullPath: '/admin/courses/create'
      preLoaderRoute: typeof AdminCoursesCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/$courseId': {
      id: '/admin/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AdminCoursesCourseIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCoursesCourseIdRoute: typeof AdminCoursesCourseIdRoute
  AdminCoursesCreateRoute: typeof AdminCoursesCreateRoute
  AdminLiveStreamIdRoute: typeof AdminLiveStreamIdRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminLiveIndexRoute: typeof AdminLiveIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminVideosIndexRoute: typeof AdminVideosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCoursesCourseIdRoute: AdminCoursesCourseIdRoute,
  AdminCoursesCreateRoute: AdminCoursesCreateRoute,
  AdminLiveStreamIdRoute: AdminLiveStreamIdRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminLiveIndexRoute: AdminLiveIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminVideosIndexRoute: AdminVideosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OtpVerificationRoute: OtpVerificationRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
